#!/usr/bin/python

import os
import sys
from BeautifulSoup import BeautifulSoup

if len(sys.argv) == 1:
    print "Usage: %s file.html" % sys.argv[0]
    sys.exit(1)

try:
    f = os.open(sys.argv[1],os.O_RDONLY)
except OSError, e:
    print "%s: Does not exists" % sys.argv[1]
    sys.exit(1)

st = os.stat(sys.argv[1])
str = os.read(f,st.st_size)
soup = BeautifulSoup(str)
print soup.prettify()
